INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (1, 'Whiskers', 'Loves to climb and explore.', 1);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (2, 'Shadow', 'Prefers quiet, dark places.', 2);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (3, 'Bella', 'Friendly and loves attention.', 3);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (4, 'Luna', 'Very playful and active.', 4);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (5, 'Oliver', 'Enjoys napping in the sun.', 5);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (6, 'Simba', 'Brave and curious.', 6);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (7, 'Chloe', 'Affectionate and gentle.', 7);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (8, 'Milo', 'Loves to chase toys.', 8);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (9, 'Max', 'Quiet and independent.', 9);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (10, 'Nala', 'Very vocal and loves to talk.', 10);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (11, 'Kitty', 'Calm and relaxed.', 1);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (12, 'Tigger', 'Adventurous and bold.', 2);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (13, 'Smokey', 'Prefers to stay indoors.', 3);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (14, 'Oscar', 'Very curious and playful.', 4);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (15, 'Ginger', 'Enjoys being pampered.', 5);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (16, 'Coco', 'Loves to cuddle.', 6);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (17, 'Misty', 'Shy but affectionate.', 7);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (18, 'Leo', 'Bold and adventurous.', 8);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (19, 'Loki', 'Mischievous and playful.', 9);
INSERT INTO public.cats_cat (id, name, description_from_owner, breed_id) VALUES (20, 'Lilly', 'Loves attention and cuddles.', 10);
